name: Build, Test & Publish (GitHub Packages)

on:
  push:
    branches: [ "**" ]
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore NugetProjects

      - name: Build (Release)
        run: dotnet build NugetProjects --configuration Release --no-restore

      - name: Run Test
        run: dotnet test NugetProjects/Tests/Tests.csproj --configuration Release --no-build

  pack-and-push:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-test
    runs-on: ubuntu-latest
    env:
      OWNER: PatrickMisti
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Extract version from tag
        id: v
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore NugetProjects/FhOoeProjectPackages/FhOoeProjectPackages.csproj

      - name: Pack
        run: |
          dotnet pack NugetProjects/FhOoeProjectPackages/FhOoeProjectPackages.csproj \
            -c Release --no-restore \
            -p:PackageVersion=${{ steps.v.outputs.version }} \
            -o ./artifacts

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ env.OWNER }}/index.json" \
            --api-key "${GITHUB_TOKEN}" \
            --skip-duplicate
